#!/bin/sh
cd `dirname $0`
sh AbsFunction/Install.sh
sh Backlash/Install.sh
sh Bias/Install.sh
sh ConstantValue/Install.sh
sh CoulombAndViscousFriction/Install.sh
sh DeadZone/Install.sh
sh DemuxFunction/Install.sh
sh Derivative/Install.sh
sh Gain/Install.sh
sh IfElse/Install.sh
sh Integrator/Install.sh
sh MinMaxFunction/Install.sh
sh MuxFunction/Install.sh
sh PIDController/Install.sh
sh Polynomial/Install.sh
sh ProductFunction/Install.sh
sh PulseGenerator/Install.sh
sh RampFunction/Install.sh
sh RandomNumber/Install.sh
sh RateLimiter/Install.sh
sh Relay/Install.sh
sh Saturation/Install.sh
sh Scope/Install.sh
sh SignFunction/Install.sh
sh SineWave/Install.sh
sh SqrtFunction/Install.sh
sh StepFunction/Install.sh
sh SumFunction/Install.sh
sh TrigonometricFunction/Install.sh
sh UnaryMinus/Install.sh
sh UniformRandomNumber/Install.sh
sh WrapToZero/Install.sh
